version: '3.3'
services:
  mysql-57:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql@123'
      MYSQL_ROOT_PASSWORD: 'mysql@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
